CHMS_AUTH_API_KEY: GET_THE_KEY_FROM_ANOTHER_DEV
PG_USERNAME: username
PG_PASSWORD:

EMAIL_USERNAME: 'username'
EMAIL_PASSWORD: 'password'
EMAIL_SERVER: 'smtp.mailgun.org'
EMAIL_PORT: '587'
EMAIL_FROM: 'noreply@localhost'
ADMIN_EMAIL: 'webmaster@northpointministries.net'

EVENTBRITE_API_TOKEN: 'YOUR_TOKEN_HERE'
REDIS_URL: 'redis://localhost:6379'

SITE_NAME: 'Regroup Online'
SITE_SHORT_NAME: 'Regroup'
SITE_COLOR1: '#00a0df'
SITE_LOGO: 'regroup-logo.png'
SITE_LOGO_SMALL: 'groups-mark.png'
SITE_LEARN_MORE: 'http://driveconference.com'
SITE_REGISTER: 'https://www.eventbrite.com/e/drive-online-2017-tickets-31259308433'
